resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.9"

resources:
  - name: spring-boot-service
    type: git
    source:
      uri: git@github.com:robin0695/concourse-ci-cd.git
      branch: master
      icon: github
      private_key: ((git-private-key))

  - name: spring-boot-service-docker-repository
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))

  - name: kubectl
    type: kubernetes
    source:
      kubeconfig: |
        apiVersion: v1
        clusters:
        - cluster:
            certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EWXhPREF5TlRreE0xb1hEVE15TURZeE5UQXlOVGt4TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjRkCmQvQmFTOURsOVd6aDRkRDVSaUQ3VjluZXRZWnpuQkkxc21aeUZjOTBVQ28xZGl2cGVBVXlETlBLZjVEYUVnTXYKVDR0SllPN05USENwcTRKdWlodjdBR0ViekFxVFk2YVBialdjR3JGb21qQ3B2N1BDSXBlTjdyZk1VQ1h5c0MwYQowMmx6Y3JmbXRWNEpHQ1pSQkREbERTUW9NU3NXVW9VUm9Ec3ozSHFCeHJCTFc4Y01ubzNqSXlPMW9xODFLZ2NVCi9MNVVjOHRBa21QUzkrTHpEZ1UwamJrTnJjcWtqZVNubHBxVjVwak13MEdSMjM2Sk1iRTlwOUxXclhOaVh5NlYKcjFRZWtvYlYvSTNxZGo0b1R0Ync5TXZnWE85WVlwbHd0RG5IUll0N1RLNGNRNDRCZHVGS2RqZnN4QkpqNVN1cQorMWM5NGRhQWVPa2tXWkhMaStNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZFRmpGN3RCVHB5MEcwcWVhbU5sTVpyTHF2WXlNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRnkrTHFwUFpMSVYveVYvNFREeQpIQkFPVlZTajBXSkkrMXdQQ2hNYVFaNERIQVBKNDBrazltQ1J5cWk1S0FHNTNTbGw4SFRvRXdVMnlQYTFtRExqClI1NTBTNko5Rjh5ZG15M2hVb0FzN1V2VXF0OHMxZzNPZmdoSWxNNVNjdVpWTG5QZHpUcjBqcFdqeks5M1NQTUQKODFxU0xXRFl6OFFuaWYvMVN3c0NEc1ErWm9KN0xqakVZWllzNGRCc2VERkR2Yjk2Wjk2YXBSZHpVZk5aRXdLRwpTdHpHTDg4QXNuMjdTaGpkN3dVazh6V1VNd1NhSnBPS2JNclBuMWV3QVBBeFIxRU5ZbTBmM2lOV21ldU9aR0kvCnUvOUFTVW8yNmxDbC90MUREL1JlNFkxZkJpbkZVZjE3THpCcFF1VHhNTi81RHNCK0lvb2Q0RkF2NS9WZDhISzIKUjBrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            server: https://192.168.10.129:6443
          name: kubernetes
        contexts:
        - context:
            cluster: kubernetes
            user: kubernetes-admin
          name: kubernetes-admin@kubernetes
        current-context: kubernetes-admin@kubernetes
        kind: Config
        preferences: {}
        users:
        - name: kubernetes-admin
          user:
            client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJWFoyQVhESDZocUV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpBMk1UZ3dNalU1TVROYUZ3MHlNekEyTVRnd01qVTVNVFZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTFudDdJT1Zmczh4N0dtcGwKUktCMW4rVXVsQllTYjNlck5nSStEWnZaVmpiQ3NUWWRGbTN2c3J2OXBQbjZPa05TVFQ5eFBZdmRNbURRYXZ6SgpBQmF1TEFVUlJ3bDBJY0lWUU96ZjRkeHZ3MXFVOHQ3dERiNENZb2RqajRYUVRkWlVBMGRRNi93MmY0dnlrc0N1Ck9XY3lhSXMrM21SSk5STWMycUFTdVdsNHgwS0lWaG1oL1VEVkp4bU1UeUpFNU1uWGpjYXhZeURDSDU2WW03QWEKSjZEU0tKalJ5eGJnaWg4UUp0UVlWNEtONzJBUUdmQWw2eDNncmNzaTg0T1RzMGdvdzlpN0ZzeHRFU09uZkJ5ZwozT2p1YkRPdWVra1h1OVk0MVZlV2k2czEycTh4Q2ZiZHJUcE1uQktmWjF5NTFKTjkzYnk1VGZEQ0g4VWgya2FVCmRvSDNIUUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSQll4ZTdRVTZjdEJ0S25tcGpaVEdheTZyMgpNakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBVkNhZ0YzUXNUN29NTmMzQ2ZrcDVFb2IwS2VyNmxLUkdOM01XCmhwK2dYUjhTUmp2TURmR2V6MVNjSEpHTzhUUG5QZmg0NXpPSEl5YmpSYVFyN0dvRzUvZkFOTkdaVFZvNEdPVXoKVmlUNWV1Q09ZK1FJelY2UjBUTklvcjBTOUxjRytEVGR4WEJRN0xuaStNVmhsNWJSQjZmVjlYL3NRdFhhUU5NNApvMFI5VzhvZHpPcU5EWEtTdkRZSjUyM0N6YmlHU0hmclVHMEdDMnBGeVpDSUI2dTJ0aDdROHc4bHFTd0JqWjV1ClJXd1F0enJHaVZNZ21yaU1aVnFHZi9aWHVaOEhZZGNaWVF2ME1UYnVGdmxBWXlRN2d1S21oUE9xZTF3ZkExOFIKdXAwU3pkbmhoRnB6ejFlclgyYklUVlZqQ1hMTFFUcVkwcFM1RFNHL1Rjc05ZeEcxV0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMW50N0lPVmZzOHg3R21wbFJLQjFuK1V1bEJZU2IzZXJOZ0krRFp2WlZqYkNzVFlkCkZtM3ZzcnY5cFBuNk9rTlNUVDl4UFl2ZE1tRFFhdnpKQUJhdUxBVVJSd2wwSWNJVlFPemY0ZHh2dzFxVTh0N3QKRGI0Q1lvZGpqNFhRVGRaVUEwZFE2L3cyZjR2eWtzQ3VPV2N5YUlzKzNtUkpOUk1jMnFBU3VXbDR4MEtJVmhtaAovVURWSnhtTVR5SkU1TW5YamNheFl5RENINTZZbTdBYUo2RFNLSmpSeXhiZ2loOFFKdFFZVjRLTjcyQVFHZkFsCjZ4M2dyY3NpODRPVHMwZ293OWk3RnN4dEVTT25mQnlnM09qdWJET3Vla2tYdTlZNDFWZVdpNnMxMnE4eENmYmQKclRwTW5CS2ZaMXk1MUpOOTNieTVUZkRDSDhVaDJrYVVkb0gzSFFJREFRQUJBb0lCQVFETW12bEgxV2lwaGR5OQp3MWVkMHhEQ213Z0hIdE14WU5DRWNqa3VGRW1ObENuQWtlWEh1dEphQ0RvY2dwZXhzdjAxVWRzK0lrbStRRnN5ClpMbCtpeVJXTy9OU2QvTkFMUHpIZGZEUmJzOXpaZHNIb2FBMFp0bXhrb1JvcXZlZStXSWx5b2VveDI1WjJIQnMKak1Eblk4blRyMW9uSHpZekdtdUJLQWtVdFVnUmxHaHZrWEF4aGxOWUJDRU10NzZkYnFEL0NRNFBId2V1My9hRAoyaXdMMmVnbUlrMEUrT3ZaZmpncGVtY3NoTTlwZXlIS0phV0pWRm1CMExtZGZpQ25Vdk9Vb1RoRHd6ZHQvUDNZCjl1RlRKZGUyWGdwWndDSGp4bjBabmI0RGI1ZXdkeXp6QUlxckVZbTN6UkZmcVRYUVQweWRJbU9BVk9nRUZPUDAKOTZYbjJwM2hBb0dCQVBDQ1A2ZlBHWHNhTkhrQ3FJRDY0RndNRHZFSnY4eGdJQ2M0b28ydFRjNnN6YzBneVdTVQo5ZVJBemhLU2xqQnlGTGFPbUtSYTJWZ1pJTzkwUXlXTUVIZ1d5bFoxV20ya3BTTzFuRTg5cnZlQ1ZFY0NFQXZICmhHMmpzbmI3TEdRa3lvMkZxU3NNYmREM0pJMTV5dENORUtoRW15VDlGTUFiTkxWK2c0VkI2OHZWQW9HQkFPUk0KRlFwK2N5SkpYa3JLbnBpanZrb0tFcXExSjNWR2hSbHgwdkRnaFhnY055d2dFbm0xTzdTc08xL2c5TUJrbUwxUworK0lXM044UnlJSS9HNysxN3dST0RmdnFZUTJJa3dXZXlZNXpEMGtTNzVaNmI2WExjYkUveHRNY1M4a2w3Um5VCmR1cTdZWTJ0R1pGaDZXOUlQRUhxT2xBc0RkZitUOVViWWJrMnFBb3BBb0dCQUxYdlVZZjN1aWJOWS9SR2RvRmIKUm0xYkVkSjB0WW85RFJXZVdoa2lpRUZYcHpjTkhrdmdBMEp2WTNQWlA1UFdPS1VBcWFkcXNnOWFzdmR3MDNxTAp3Y21XTStuRFRHeTBwOWVqZ21MUEhwUk5Hc084WTdjRmJzQWhuTmMwbWhnSFhOSkIwZjZtb0V2N0tNTjg1bGRzCjNyVHJjUkZDQVhoeEhDWlBWZDV3UjVjaEFvR0JBSnM4RExhbEF2N1dhckpxa21yeU5Jczl6REdkbXFZSS9Lb3YKbHFMSjJKZXlmK1dXTFZucTNSMWVXOFUzUHRXdjBaZ3kzQ21CS0ZEYVU4QVV6M2FOYkdnOTl3NUw4aEIweEp2Mgp1OUVMOWVIWGFXaWwrbEwvUW1DbklEZ2VybjJwTjA3d0JLaGFIOXhwVHRCbmhvWnYxT0Z4TnBPYlVSS0V6NTMxCnozNVVadkQ1QW9HQUFVTU5sd1JsVVFxSTRlMWw3TjY5SWhKWVZPOGJ0YlJReEJJZlBUeXkyUXFIZVlXOVdycVAKbnFUYThpRFdVbHZoSkd5cGZjQkV2QWlpaXJOUE1XQUkrRDNneDZ1bmphd3Q5UEkxRjBETWlQMHVlRk5UUUp4NApTYzRVZSs5MDdwQ3pwZkxpczZjTVV4dldFc2Y2aHJySXJ3bFdmWXk4d2orSm9SOEliemZPTVowPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

jobs:
  - name: test
    public: true

    plan:
      - get: spring-boot-service
        trigger: true
      - task: mvn-test
        file: "spring-boot-service/concourse_ci/tasks/maven-test.yml"

  - name: package
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [test]
      - task: mvn-package
        file: "spring-boot-service/concourse_ci/tasks/maven-package.yml"
      - put: spring-boot-service-docker-repository
        params:
          build: spring-boot-service-out

  - name: deploy
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [package]
      - put: kubectl
        params:
          kubectl: apply -f spring-boot-service/spring-boot-deploy.yaml
